/// 57+ font pairings from ui-ux-pro-max/typography.csv
class FontPairings {
  FontPairings._();

  static const all = [
  FontPairing('Classic Elegant', 'Serif + Sans', 'Playfair Display', 'Inter', 'elegant, luxury, sophisticated, timeless, premium, editorial', 'Luxury brands, fashion, spa, beauty, editorial, magazines, high-end e-commerce', '@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap\');', 'High contrast between elegant heading and clean body. Perfect for luxury/premium.'),
  FontPairing('Modern Professional', 'Sans + Sans', 'Poppins', 'Open Sans', 'modern, professional, clean, corporate, friendly, approachable', 'SaaS, corporate sites, business apps, startups, professional services', '@import url(\'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap\');', 'Geometric Poppins for headings, humanist Open Sans for readability.'),
  FontPairing('Tech Startup', 'Sans + Sans', 'Space Grotesk', 'DM Sans', 'tech, startup, modern, innovative, bold, futuristic', 'Tech companies, startups, SaaS, developer tools, AI products', '@import url(\'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Space+Grotesk:wght@400;500;600;700&display=swap\');', 'Space Grotesk has unique character, DM Sans is highly readable.'),
  FontPairing('Editorial Classic', 'Serif + Serif', 'Cormorant Garamond', 'Libre Baskerville', 'editorial, classic, literary, traditional, refined, bookish', 'Publishing, blogs, news sites, literary magazines, book covers', '@import url(\'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Libre+Baskerville:wght@400;700&display=swap\');', 'All-serif pairing for traditional editorial feel.'),
  FontPairing('Minimal Swiss', 'Sans + Sans', 'Inter', 'Inter', 'minimal, clean, swiss, functional, neutral, professional', 'Dashboards, admin panels, documentation, enterprise apps, design systems', '@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\');', 'Single font family with weight variations. Ultimate simplicity.'),
  FontPairing('Playful Creative', 'Display + Sans', 'Fredoka', 'Nunito', 'playful, friendly, fun, creative, warm, approachable', 'Children\'s apps, educational, gaming, creative tools, entertainment', '@import url(\'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap\');', 'Rounded, friendly fonts perfect for playful UIs.'),
  FontPairing('Bold Statement', 'Display + Sans', 'Bebas Neue', 'Source Sans 3', 'bold, impactful, strong, dramatic, modern, headlines', 'Marketing sites, portfolios, agencies, event pages, sports', '@import url(\'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Source+Sans+3:wght@300;400;500;600;700&display=swap\');', 'Bebas Neue for large headlines only. All-caps display font.'),
  FontPairing('Wellness Calm', 'Serif + Sans', 'Lora', 'Raleway', 'calm, wellness, health, relaxing, natural, organic', 'Health apps, wellness, spa, meditation, yoga, organic brands', '@import url(\'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Raleway:wght@300;400;500;600;700&display=swap\');', 'Lora\'s organic curves with Raleway\'s elegant simplicity.'),
  FontPairing('Developer Mono', 'Mono + Sans', 'JetBrains Mono', 'IBM Plex Sans', 'code, developer, technical, precise, functional, hacker', 'Developer tools, documentation, code editors, tech blogs, CLI apps', '@import url(\'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap\');', 'JetBrains for code, IBM Plex for UI. Developer-focused.'),
  FontPairing('Retro Vintage', 'Display + Serif', 'Abril Fatface', 'Merriweather', 'retro, vintage, nostalgic, dramatic, decorative, bold', 'Vintage brands, breweries, restaurants, creative portfolios, posters', '@import url(\'https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Merriweather:wght@300;400;700&display=swap\');', 'Abril Fatface for hero headlines only. High-impact vintage feel.'),
  FontPairing('Geometric Modern', 'Sans + Sans', 'Outfit', 'Work Sans', 'geometric, modern, clean, balanced, contemporary, versatile', 'General purpose, portfolios, agencies, modern brands, landing pages', '@import url(\'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap\');', 'Both geometric but Outfit more distinctive for headings.'),
  FontPairing('Luxury Serif', 'Serif + Sans', 'Cormorant', 'Montserrat', 'luxury, high-end, fashion, elegant, refined, premium', 'Fashion brands, luxury e-commerce, jewelry, high-end services', '@import url(\'https://fonts.googleapis.com/css2?family=Cormorant:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap\');', 'Cormorant\'s elegance with Montserrat\'s geometric precision.'),
  FontPairing('Friendly SaaS', 'Sans + Sans', 'Plus Jakarta Sans', 'Plus Jakarta Sans', 'friendly, modern, saas, clean, approachable, professional', 'SaaS products, web apps, dashboards, B2B, productivity tools', '@import url(\'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap\');', 'Single versatile font. Modern alternative to Inter.'),
  FontPairing('News Editorial', 'Serif + Sans', 'Newsreader', 'Roboto', 'news, editorial, journalism, trustworthy, readable, informative', 'News sites, blogs, magazines, journalism, content-heavy sites', '@import url(\'https://fonts.googleapis.com/css2?family=Newsreader:wght@400;500;600;700&family=Roboto:wght@300;400;500;700&display=swap\');', 'Newsreader designed for long-form reading. Roboto for UI.'),
  FontPairing('Handwritten Charm', 'Script + Sans', 'Caveat', 'Quicksand', 'handwritten, personal, friendly, casual, warm, charming', 'Personal blogs, invitations, creative portfolios, lifestyle brands', '@import url(\'https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&family=Quicksand:wght@300;400;500;600;700&display=swap\');', 'Use Caveat sparingly for accents. Quicksand for body.'),
  FontPairing('Corporate Trust', 'Sans + Sans', 'Lexend', 'Source Sans 3', 'corporate, trustworthy, accessible, readable, professional, clean', 'Enterprise, government, healthcare, finance, accessibility-focused', '@import url(\'https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;500;600;700&family=Source+Sans+3:wght@300;400;500;600;700&display=swap\');', 'Lexend designed for readability. Excellent accessibility.'),
  FontPairing('Brutalist Raw', 'Mono + Mono', 'Space Mono', 'Space Mono', 'brutalist, raw, technical, monospace, minimal, stark', 'Brutalist designs, developer portfolios, experimental, tech art', '@import url(\'https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap\');', 'All-mono for raw brutalist aesthetic. Limited weights.'),
  FontPairing('Fashion Forward', 'Sans + Sans', 'Syne', 'Manrope', 'fashion, avant-garde, creative, bold, artistic, edgy', 'Fashion brands, creative agencies, art galleries, design studios', '@import url(\'https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&family=Syne:wght@400;500;600;700&display=swap\');', 'Syne\'s unique character for headlines. Manrope for readability.'),
  FontPairing('Soft Rounded', 'Sans + Sans', 'Varela Round', 'Nunito Sans', 'soft, rounded, friendly, approachable, warm, gentle', 'Children\'s products, pet apps, friendly brands, wellness, soft UI', '@import url(\'https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;500;600;700&family=Varela+Round&display=swap\');', 'Both rounded and friendly. Perfect for soft UI designs.'),
  FontPairing('Premium Sans', 'Sans + Sans', 'Satoshi', 'General Sans', 'premium, modern, clean, sophisticated, versatile, balanced', 'Premium brands, modern agencies, SaaS, portfolios, startups', '@import url(\'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap\');', 'Note: Satoshi/General Sans on Fontshare. DM Sans as Google alternative.'),
  FontPairing('Vietnamese Friendly', 'Sans + Sans', 'Be Vietnam Pro', 'Noto Sans', 'vietnamese, international, readable, clean, multilingual, accessible', 'Vietnamese sites, multilingual apps, international products', '@import url(\'https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@300;400;500;600;700&family=Noto+Sans:wght@300;400;500;600;700&display=swap\');', 'Be Vietnam Pro excellent Vietnamese support. Noto as fallback.'),
  FontPairing('Japanese Elegant', 'Serif + Sans', 'Noto Serif JP', 'Noto Sans JP', 'japanese, elegant, traditional, modern, multilingual, readable', 'Japanese sites, Japanese restaurants, cultural sites, anime/manga', '@import url(\'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&family=Noto+Serif+JP:wght@400;500;600;700&display=swap\');', 'Noto fonts excellent Japanese support. Traditional + modern feel.'),
  FontPairing('Korean Modern', 'Sans + Sans', 'Noto Sans KR', 'Noto Sans KR', 'korean, modern, clean, professional, multilingual, readable', 'Korean sites, K-beauty, K-pop, Korean businesses, multilingual', '@import url(\'https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\');', 'Clean Korean typography. Single font with weight variations.'),
  FontPairing('Chinese Traditional', 'Serif + Sans', 'Noto Serif TC', 'Noto Sans TC', 'chinese, traditional, elegant, cultural, multilingual, readable', 'Traditional Chinese sites, cultural content, Taiwan/Hong Kong markets', '@import url(\'https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@300;400;500;700&family=Noto+Serif+TC:wght@400;500;600;700&display=swap\');', 'Traditional Chinese character support. Elegant pairing.'),
  FontPairing('Chinese Simplified', 'Sans + Sans', 'Noto Sans SC', 'Noto Sans SC', 'chinese, simplified, modern, professional, multilingual, readable', 'Simplified Chinese sites, mainland China market, business apps', '@import url(\'https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300;400;500;700&display=swap\');', 'Simplified Chinese support. Clean modern look.'),
  FontPairing('Arabic Elegant', 'Serif + Sans', 'Noto Naskh Arabic', 'Noto Sans Arabic', 'arabic, elegant, traditional, cultural, RTL, readable', 'Arabic sites, Middle East market, Islamic content, bilingual sites', '@import url(\'https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&family=Noto+Sans+Arabic:wght@300;400;500;700&display=swap\');', 'RTL support. Naskh for traditional, Sans for modern Arabic.'),
  FontPairing('Thai Modern', 'Sans + Sans', 'Noto Sans Thai', 'Noto Sans Thai', 'thai, modern, readable, clean, multilingual, accessible', 'Thai sites, Southeast Asia, tourism, Thai restaurants', '@import url(\'https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@300;400;500;700&display=swap\');', 'Clean Thai typography. Excellent readability.'),
  FontPairing('Hebrew Modern', 'Sans + Sans', 'Noto Sans Hebrew', 'Noto Sans Hebrew', 'hebrew, modern, RTL, clean, professional, readable', 'Hebrew sites, Israeli market, Jewish content, bilingual sites', '@import url(\'https://fonts.googleapis.com/css2?family=Noto+Sans+Hebrew:wght@300;400;500;700&display=swap\');', 'RTL support. Clean modern Hebrew typography.'),
  FontPairing('Legal Professional', 'Serif + Sans', 'EB Garamond', 'Lato', 'legal, professional, traditional, trustworthy, formal, authoritative', 'Law firms, legal services, contracts, formal documents, government', '@import url(\'https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600;700&family=Lato:wght@300;400;700&display=swap\');', 'EB Garamond for authority. Lato for clean body text.'),
  FontPairing('Medical Clean', 'Sans + Sans', 'Figtree', 'Noto Sans', 'medical, clean, accessible, professional, healthcare, trustworthy', 'Healthcare, medical clinics, pharma, health apps, accessibility', '@import url(\'https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;500;600;700&family=Noto+Sans:wght@300;400;500;700&display=swap\');', 'Clean, accessible fonts for medical contexts.'),
  FontPairing('Financial Trust', 'Sans + Sans', 'IBM Plex Sans', 'IBM Plex Sans', 'financial, trustworthy, professional, corporate, banking, serious', 'Banks, finance, insurance, investment, fintech, enterprise', '@import url(\'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&display=swap\');', 'IBM Plex conveys trust and professionalism. Excellent for data.'),
  FontPairing('Real Estate Luxury', 'Serif + Sans', 'Cinzel', 'Josefin Sans', 'real estate, luxury, elegant, sophisticated, property, premium', 'Real estate, luxury properties, architecture, interior design', '@import url(\'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&family=Josefin+Sans:wght@300;400;500;600;700&display=swap\');', 'Cinzel\'s elegance for headlines. Josefin for modern body.'),
  FontPairing('Restaurant Menu', 'Serif + Sans', 'Playfair Display SC', 'Karla', 'restaurant, menu, culinary, elegant, foodie, hospitality', 'Restaurants, cafes, food blogs, culinary, hospitality', '@import url(\'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display+SC:wght@400;700&display=swap\');', 'Small caps Playfair for menu headers. Karla for descriptions.'),
  FontPairing('Art Deco', 'Display + Sans', 'Poiret One', 'Didact Gothic', 'art deco, vintage, 1920s, elegant, decorative, gatsby', 'Vintage events, art deco themes, luxury hotels, classic cocktails', '@import url(\'https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Poiret+One&display=swap\');', 'Poiret One for art deco headlines only. Didact for body.'),
  FontPairing('Magazine Style', 'Serif + Sans', 'Libre Bodoni', 'Public Sans', 'magazine, editorial, publishing, refined, journalism, print', 'Magazines, online publications, editorial content, journalism', '@import url(\'https://fonts.googleapis.com/css2?family=Libre+Bodoni:wght@400;500;600;700&family=Public+Sans:wght@300;400;500;600;700&display=swap\');', 'Bodoni\'s editorial elegance. Public Sans for clean UI.'),
  FontPairing('Crypto/Web3', 'Sans + Sans', 'Orbitron', 'Exo 2', 'crypto, web3, futuristic, tech, blockchain, digital', 'Crypto platforms, NFT, blockchain, web3, futuristic tech', '@import url(\'https://fonts.googleapis.com/css2?family=Exo+2:wght@300;400;500;600;700&family=Orbitron:wght@400;500;600;700&display=swap\');', 'Orbitron for futuristic headers. Exo 2 for readable body.'),
  FontPairing('Gaming Bold', 'Display + Sans', 'Russo One', 'Chakra Petch', 'gaming, bold, action, esports, competitive, energetic', 'Gaming, esports, action games, competitive sports, entertainment', '@import url(\'https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300;400;500;600;700&family=Russo+One&display=swap\');', 'Russo One for impact. Chakra Petch for techy body text.'),
  FontPairing('Indie/Craft', 'Display + Sans', 'Amatic SC', 'Cabin', 'indie, craft, handmade, artisan, organic, creative', 'Craft brands, indie products, artisan, handmade, organic products', '@import url(\'https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Cabin:wght@400;500;600;700&display=swap\');', 'Amatic for handwritten feel. Cabin for readable body.'),
  FontPairing('Startup Bold', 'Sans + Sans', 'Clash Display', 'Satoshi', 'startup, bold, modern, innovative, confident, dynamic', 'Startups, pitch decks, product launches, bold brands', '@import url(\'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=Rubik:wght@300;400;500;600;700&display=swap\');', 'Note: Clash Display on Fontshare. Outfit as Google alternative.'),
  FontPairing('E-commerce Clean', 'Sans + Sans', 'Rubik', 'Nunito Sans', 'ecommerce, clean, shopping, product, retail, conversion', 'E-commerce, online stores, product pages, retail, shopping', '@import url(\'https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;500;600;700&family=Rubik:wght@300;400;500;600;700&display=swap\');', 'Clean readable fonts perfect for product descriptions.'),
  FontPairing('Academic/Research', 'Serif + Sans', 'Crimson Pro', 'Atkinson Hyperlegible', 'academic, research, scholarly, accessible, readable, educational', 'Universities, research papers, academic journals, educational', '@import url(\'https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&family=Crimson+Pro:wght@400;500;600;700&display=swap\');', 'Crimson for scholarly headlines. Atkinson for accessibility.'),
  FontPairing('Dashboard Data', 'Mono + Sans', 'Fira Code', 'Fira Sans', 'dashboard, data, analytics, code, technical, precise', 'Dashboards, analytics, data visualization, admin panels', '@import url(\'https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600;700&family=Fira+Sans:wght@300;400;500;600;700&display=swap\');', 'Fira family cohesion. Code for data, Sans for labels.'),
  FontPairing('Music/Entertainment', 'Display + Sans', 'Righteous', 'Poppins', 'music, entertainment, fun, energetic, bold, performance', 'Music platforms, entertainment, events, festivals, performers', '@import url(\'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Righteous&display=swap\');', 'Righteous for bold entertainment headers. Poppins for body.'),
  FontPairing('Minimalist Portfolio', 'Sans + Sans', 'Archivo', 'Space Grotesk', 'minimal, portfolio, designer, creative, clean, artistic', 'Design portfolios, creative professionals, minimalist brands', '@import url(\'https://fonts.googleapis.com/css2?family=Archivo:wght@300;400;500;600;700&family=Space+Grotesk:wght@300;400;500;600;700&display=swap\');', 'Space Grotesk for distinctive headers. Archivo for clean body.'),
  FontPairing('Kids/Education', 'Display + Sans', 'Baloo 2', 'Comic Neue', 'kids, education, playful, friendly, colorful, learning', 'Children\'s apps, educational games, kid-friendly content', '@import url(\'https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;500;600;700&family=Comic+Neue:wght@300;400;700&display=swap\');', 'Fun, playful fonts for children. Comic Neue is readable comic style.'),
  FontPairing('Wedding/Romance', 'Script + Serif', 'Great Vibes', 'Cormorant Infant', 'wedding, romance, elegant, script, invitation, feminine', 'Wedding sites, invitations, romantic brands, bridal', '@import url(\'https://fonts.googleapis.com/css2?family=Cormorant+Infant:wght@300;400;500;600;700&family=Great+Vibes&display=swap\');', 'Great Vibes for elegant accents. Cormorant for readable text.'),
  FontPairing('Science/Tech', 'Sans + Sans', 'Exo', 'Roboto Mono', 'science, technology, research, data, futuristic, precise', 'Science, research, tech documentation, data-heavy sites', '@import url(\'https://fonts.googleapis.com/css2?family=Exo:wght@300;400;500;600;700&family=Roboto+Mono:wght@300;400;500;700&display=swap\');', 'Exo for modern tech feel. Roboto Mono for code/data.'),
  FontPairing('Accessibility First', 'Sans + Sans', 'Atkinson Hyperlegible', 'Atkinson Hyperlegible', 'accessible, readable, inclusive, WCAG, dyslexia-friendly, clear', 'Accessibility-critical sites, government, healthcare, inclusive design', '@import url(\'https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&display=swap\');', 'Designed for maximum legibility. Excellent for accessibility.'),
  FontPairing('Sports/Fitness', 'Sans + Sans', 'Barlow Condensed', 'Barlow', 'sports, fitness, athletic, energetic, condensed, action', 'Sports, fitness, gyms, athletic brands, competition', '@import url(\'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;500;600;700&family=Barlow:wght@300;400;500;600;700&display=swap\');', 'Condensed for impact headlines. Regular Barlow for body.'),
  FontPairing('Luxury Minimalist', 'Serif + Sans', 'Bodoni Moda', 'Jost', 'luxury, minimalist, high-end, sophisticated, refined, premium', 'Luxury minimalist brands, high-end fashion, premium products', '@import url(\'https://fonts.googleapis.com/css2?family=Bodoni+Moda:wght@400;500;600;700&family=Jost:wght@300;400;500;600;700&display=swap\');', 'Bodoni\'s high contrast elegance. Jost for geometric body.'),
  FontPairing('Tech/HUD Mono', 'Mono + Mono', 'Share Tech Mono', 'Fira Code', 'tech, futuristic, hud, sci-fi, data, monospaced, precise', 'Sci-fi interfaces, developer tools, cybersecurity, dashboards', '@import url(\'https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&family=Share+Tech+Mono&display=swap\');', 'Share Tech Mono has that classic sci-fi look.'),
  FontPairing('Pixel Retro', 'Display + Sans', 'Press Start 2P', 'VT323', 'pixel, retro, gaming, 8-bit, nostalgic, arcade', 'Pixel art games, retro websites, creative portfolios', '@import url(\'https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&display=swap\');', 'Press Start 2P is very wide/large. VT323 is better for body text.'),
  FontPairing('Neubrutalist Bold', 'Display + Sans', 'Lexend Mega', 'Public Sans', 'bold, neubrutalist, loud, strong, geometric, quirky', 'Neubrutalist designs, Gen Z brands, bold marketing', '@import url(\'https://fonts.googleapis.com/css2?family=Lexend+Mega:wght@100..900&family=Public+Sans:wght@100..900&display=swap\');', 'Lexend Mega has distinct character and variable weight.'),
  FontPairing('Academic/Archival', 'Serif + Serif', 'EB Garamond', 'Crimson Text', 'academic, old-school, university, research, serious, traditional', 'University sites, archives, research papers, history', '@import url(\'https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&family=EB+Garamond:wght@400;500;600;700;800&display=swap\');', 'Classic academic aesthetic. Very legible.'),
  FontPairing('Spatial Clear', 'Sans + Sans', 'Inter', 'Inter', 'spatial, legible, glass, system, clean, neutral', 'Spatial computing, AR/VR, glassmorphism interfaces', '@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap\');', 'Optimized for readability on dynamic backgrounds.'),
  FontPairing('Kinetic Motion', 'Display + Mono', 'Syncopate', 'Space Mono', 'kinetic, motion, futuristic, speed, wide, tech', 'Music festivals, automotive, high-energy brands', '@import url(\'https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syncopate:wght@400;700&display=swap\');', 'Syncopate\'s wide stance works well with motion effects.'),
  FontPairing('Gen Z Brutal', 'Display + Sans', 'Anton', 'Epilogue', 'brutal, loud, shouty, meme, internet, bold', 'Gen Z marketing, streetwear, viral campaigns', '@import url(\'https://fonts.googleapis.com/css2?family=Anton&family=Epilogue:wght@400;500;600;700&display=swap\');', 'Anton is impactful and condensed. Good for stickers/badges.57'),
  FontPairing('Minimalist Monochrome Editorial', 'Serif + Serif + Mono (Triple Stack)', 'Playfair Display', 'Source Serif 4', 'monochrome, editorial, austere, typographic, pocket manifesto, luxury, high contrast, brutalist mobile', 'Luxury fashion mobile apps, editorial publications, digital exhibitions, portfolio apps, high-contrast e-reader aesthetics', '@import url(\'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=Source+Serif+4:ital,wght@0,300;0,400;0,600;1,300&display=swap\');', 'Triple stack: Playfair Display 900 tracking-tighter leading-[0.9] for heroes (text-5xl–text-6xl breaks words graphically). Source Serif 4 300–600 for body legibility. JetBrains Mono 400–500 uppercase tracking-widest for tags/dates/labels. NO UI sans-serif — 100% serif/mono.'),
  FontPairing('Modern Dark Cinema (Inter System)', 'Sans + Mono', 'Inter', 'Inter', 'dark, cinematic, technical, precision, clean, premium, developer, professional, high-end utility', 'Developer tools, fintech/trading, AI dashboards, streaming platforms, high-end productivity apps', '@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\');', 'Single-family precision system: Inter 700 (-1.5 tracking) for Display 48pt; Inter 600 (-0.5 tracking) for H1 32pt / H2 24pt; Inter 400 for body 16pt; Inter 500 uppercase +1.2 tracking for labels/mono. Gradient text via mask-view + react-native-linear-gradient (#FFFFFF → rgba(255,255,255,0.7)) on major headers.'),
  FontPairing('SaaS Mobile Boutique (Calistoga + Inter)', 'Display Serif + Sans + Mono', 'Calistoga', 'Inter', 'saas, boutique, electric, warm, editorial, bold, premium, fintech, business, dual font, human warmth', 'B2B SaaS mobile, fintech apps, analytics dashboards, marketing tools, operations platforms', '@import url(\'https://fonts.googleapis.com/css2?family=Calistoga:ital@0;1&family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap\');', 'Tri-stack: Calistoga (adds human warmth) for heroes 36–42pt leading-1.1; Inter 400–600 for body/UI 16–18pt; JetBrains Mono 12pt uppercase tracking-[1.5] for data labels and section badges. Scale: Hero 36–42pt, Section H2 28–32pt, Body 16–18pt, Label 12pt. Avoid italic Calistoga except editorial callouts.'),
  FontPairing('Terminal CLI Monospace', 'Mono + Mono (Single Family)', 'JetBrains Mono', 'JetBrains Mono', 'terminal, cli, hacker, monospace, matrix, developer, retro-future, command line, precision, OLED', 'Developer tools, Web3/blockchain apps, hacker aesthetic, sci-fi games, ARG, security tools, geek-culture portfolios', '@import url(\'https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,500;1,400&display=swap\');', 'Single monospace system: use ONLY JetBrains Mono (or SpaceMono-Regular as system fallback). Strict sizes: 12pt / 14pt / 16pt only — no in-between. Weight: 400 normal (bold ruins mono character). Line height: 1.2x font size for information density. Letter spacing: normal (monospaced auto-spacing). All UI labels uppercase. ASCII borders and text-based progress bars.'),
  FontPairing('Kinetic Brutalism (Space Grotesk)', 'Geometric Sans (Single Dominant)', 'Space Grotesk', 'Space Grotesk', 'kinetic, brutalist, aggressive, uppercase, oversized, display, motion, street, bold, high-energy, zine', 'Music/culture apps, sports platforms, brand flagship mobile, performance dashboards, underground product drops', '@import url(\'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap\');', 'Dominant single-family system: Space Grotesk 700–900 for ALL display. Scale: Hero 60–120pt (windowWidth/375*size), Section 40–50pt, Card titles 28–32pt, Body 18–20pt, Labels 12pt. ALL display/buttons/nav: UPPERCASE, letterSpacing -1 (large) / +2 (labels), lineHeight 0.9–1.1x. Use Inter as fallback. Font scale must use PixelRatio helper for responsive sizing.'),
  FontPairing('Flat Design Mobile (System Bold)', 'Sans + Sans', 'Inter', 'Inter', 'flat, clean, system, bold, geometric, cross-platform, icon, poster, minimal, functional, responsive', 'Cross-platform apps, dashboards, system UI, onboarding, marketing pages, informational apps, icon-heavy interfaces', '@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap\');', 'System-first strategy: Inter as primary, falls back to system SF/Roboto on iOS/Android. Scale: Headlines fontWeight 800 letterSpacing -0.5; Subheadings fontWeight 600 fontSize 18; Body fontWeight 400 lineHeight 24; Labels fontWeight 700 uppercase letterSpacing 1. Thick weights carry all hierarchy since there are no shadows. Use aggressive size contrast (poster rule: body 16pt vs headline 40pt+). Avoid italic.'),
  FontPairing('Material You MD3 (Roboto System)', 'Sans (System Default)', 'Roboto', 'Roboto', 'material design 3, md3, android, google, tonal, friendly, rounded, accessible, adaptive', 'Android apps, cross-platform tools, productivity software, data-heavy B2B dashboards, enterprise mobile', '@import url(\'https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap\');', 'MD3 type scale: Display Large 56px/400/64px. Headline Large 32px/500/40px. Title Large 22px/500/28px. Body Large 16px/400/24px. Label Medium 12px/500/16px. Buttons and Labels: letterSpacing 0.1px. Use system Roboto on Android; load from Google Fonts for iOS parity. Never use custom weights beyond 300–700.'),
  FontPairing('Neo Brutalism Mobile (Space Grotesk Heavy)', 'Geometric Sans (Bold-Only)', 'Space Grotesk', 'Space Grotesk', 'neo brutalism, pop art, loud, bold, heavy, stickers, mechanical, high contrast, cream, gen-z', 'Creative tools, Gen-Z marketing, e-commerce for youth culture, content portfolios, collage-style apps', '@import url(\'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@700&display=swap\');', 'Strictly 700 (Bold) and 900 (Black/Heavy) ONLY — never Regular or Light. Display: 48–64px. Heading: 24–32px. Body: 18–20px (stays heavy for brutalist density). Labels: 14px ALL CAPS letterSpacing 2. All buttons and navigation: uppercase. System bold as fallback. No italic, no thin weights.'),
  FontPairing('Bold Typography Mobile (Inter-Tight Poster)', 'Sans + Serif (Display) + Mono', 'Inter', 'Playfair Display', 'bold typography, editorial, poster, near-black, vermillion, luxury, type-as-hero, manifesto, high-contrast', 'Creative brand flagships, reading platforms, event apps, flash pages, luxury mobile experiences', '@import url(\'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&family=JetBrains+Mono:wght@400&family=Playfair+Display:ital@1&display=swap\');', 'Tri-stack: Inter 600–800 for all UI (letterSpacing -1.5px heroes, -0.5px subheads). Playfair Display Italic ONLY for pull quotes. JetBrains Mono for labels and stats. Scale: 12px labels, 16px body, 22px sub, 32px section, 40px H2, 56px H1, 72px Hero Statement. 5:1 ratio H1:Body is mandatory. lineHeight 1.1 headlines, 1.6 body. Underlines (2–3pt accent) replace buttons for interactions.'),
  FontPairing('Academia Mobile (Cormorant + Crimson + Cinzel)', 'Serif + Book Serif + Engraved (Triple Stack)', 'Cormorant Garamond', 'Crimson Pro', 'academia, library, mahogany, parchment, brass, scholarly, prestige, antique, victorian, leather', 'Knowledge management apps, scholarly reading tools, personal brand portfolios, RPG games, cultural community platforms', '@import url(\'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600&family=Cormorant+Garamond:ital,wght@0,300;0,500;0,700;1,300;1,500&family=Crimson+Pro:ital,wght@0,300;0,400;0,600;1,300;1,400&display=swap\');', 'Triple-stack: Cormorant Garamond Medium for all headings (32–40px tight leading). Crimson Pro Regular for body reading text (16–18px, lineHeight 24–26px). Cinzel SemiBold for ALL-CAPS labels, overlines, section prefixes (10–12px, letterSpacing 2–3px). Drop caps: first letter 60px Cinzel in Brass #C9A962. Section prefix: VOLUME I/II/III in Cinzel 10px. NO sans-serif anywhere.'),
  FontPairing('Cyberpunk Mobile (Orbitron + JetBrains Mono)', 'Tech Display + Mono', 'Orbitron', 'JetBrains Mono', 'cyberpunk, neon, glitch, hud, sci-fi, dark, matrix green, magenta, chamfered, tactical', 'Gaming companion apps, fintech/crypto, data visualization, dark brand apps, cyberpunk narrative games', '@import url(\'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&family=Orbitron:wght@700;900&display=swap\');', 'Dual-stack: Orbitron 700–900 for H1 (42px uppercase letterSpacing 4, fontWeight 900). JetBrains Mono 400–500 for all body/data text (14px letterSpacing 1). Labels: 10px uppercase opacity 0.7. Heading scale aggressive: H1 42px, H2 28px, Section 20px. Body 14px monospace only. NO mixed sans-serif. Fallback: monospace system font. Orbitron requires loading — use NativeWind or useFonts hook.'),
  FontPairing('Web3 Bitcoin DeFi (Space Grotesk + Inter + Mono)', 'Geometric Sans + Sans + Mono (Triple)', 'Space Grotesk', 'Inter', 'web3, bitcoin, defi, digital gold, fintech, crypto, trustless, luminescent, precision, dark', 'DeFi protocols and wallets, NFT platforms, metaverse social apps, high-tech brand landing pages', '@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&family=Space+Grotesk:wght@500;600;700&display=swap\');', 'Tri-stack: Space Grotesk 600–700 for headings (geometric, technical character). Inter 400–600 for all body and UI text (high legibility). JetBrains Mono Medium for all data/stats/prices/hashes (technical accuracy). Buttons: Inter Bold uppercase letterSpacing 1.5. Balance figures use MaskedView gradient text (orange→gold). Heading scale: H1 36–42px, H2 24–28px, body 16–18px, mono labels 12–14px.'),
  FontPairing('Claymorphism Mobile (Nunito + DM Sans)', 'Display Rounded + Geometric Sans', 'Nunito', 'DM Sans', 'claymorphism, clay, rounded, playful, candy, bubbly, soft, 3d, children, education, tactile, spring, nunito, dm sans', 'Children education apps, teen social, brand mascot apps, creative tools, fintech gamification', '@import url(\'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Nunito:ital,wght@0,700;0,800;0,900;1,700&display=swap\');', 'Dual-stack: Nunito Black (900) or ExtraBold (800) for ALL headings — rounded terminals are mandatory. DM Sans Medium (500) for body text — clean and geometric. Scale: Hero 48px lineHeight 52 letterSpacing -1. Section Title 32px lineHeight 38. Card Title 22px lineHeight 28. Body 16px lineHeight 24. Never use Nunito for body text (too decorative at small sizes). Never use weights below 700 for any heading. includeFontPadding: false on all Nunito Text components for vertical centering in rounded buttons.'),
  FontPairing('Enterprise SaaS Mobile (Plus Jakarta Sans)', 'Geometric Sans (Single Family)', 'Plus Jakarta Sans', 'Plus Jakarta Sans', 'enterprise, saas, b2b, professional, indigo, modern, approachable, legible, ios dynamic type, android scaling', 'B2B SaaS apps, productivity tools, government and finance mobile apps, admin dashboards, enterprise onboarding', '@import url(\'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,400;0,600;0,700;0,800;1,400&display=swap\');', 'Single-family system: Plus Jakarta Sans balances professional authority with mobile approachability. Weight scale: ExtraBold 800 for screen titles/hero (line height 1.1–1.2). Bold 700 for section headers. SemiBold 600 for card titles and buttons. Regular 400 for body text (line height 1.4–1.5). Must support iOS Dynamic Type and Android font scaling — never hardcode pixel sizes without respecting system font scale. Button text: uppercase, letterSpacing 0.5. Caption: 12px Regular. Muted: Slate 500 #64748B.'),
  FontPairing('Sketch Hand-Drawn Mobile (Kalam + Patrick Hand)', 'Handwritten + Handwritten (Dual)', 'Kalam', 'Patrick Hand', 'sketch, hand-drawn, handwriting, human, imperfect, organic, paper, kalam, patrick hand, education, journal, creative', 'Journaling apps, prototype tools, children\'s picturebook apps, creative platforms, gamified puzzle apps', '@import url(\'https://fonts.googleapis.com/css2?family=Kalam:wght@400;700&family=Patrick+Hand&display=swap\');', 'Dual handwritten stack: Kalam Bold (700) for all headings — high visual weight, felt-tip marker aesthetic, conveys intentional messiness. Patrick Hand Regular for all body text — highly legible at mobile sizes while remaining distinctly human. Scale: Heading 28–36px with lineHeight adjusted for descenders. Body 16–18px lineHeight 1.5. Labels 14px. Vary font sizes slightly between adjacent elements for spontaneous feel. Avoid alignment: \'center\' for long body text — left-aligned reads more naturally. Both fonts require useFonts loading in Expo. Never use these fonts for financial figures or legal text.'),
  FontPairing('Neumorphism Mobile (Plus Jakarta Sans + System)', 'Geometric Sans (System Fallback)', 'Plus Jakarta Sans', 'Plus Jakarta Sans', 'neumorphism, soft ui, monochromatic, cool grey, minimal, physical, depth, ceramic, system font, utility', 'Smart home controls, minimal tools, aesthetic dashboards, health monitors, brand showcase pages', '@import url(\'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,700;1,400&display=swap\');', 'Single-family or System fallback: Plus Jakarta Sans Bold/Medium pairs beautifully with the monochromatic #E0E5EC surface — subtle geometry without competing with the depth effect. Heading: 24–32px Bold (700), letterSpacing -0.5 for modern premium feel. Body: 16px Medium (500), lineHeight 1.4. Caption: 12px Regular (400). Use Text Primary #3D4852 (7.5:1 contrast against #E0E5EC) for all primary text. Use Text Muted #6B7280 (4.6:1 contrast) for secondary text. Accent color #6C63FF only on active labels or focus indicators. Never use italic or thin weights — they lose legibility against the embossed background. System (SF Pro / Roboto) is an acceptable fallback for performance-sensitive implementations.')
  ];

  static FontPairing? find(String query) {
    final q = query.toLowerCase();
    for (final p in all) {
      if (p.name.toLowerCase().contains(q) || p.mood.contains(q) || p.bestFor.contains(q)) return p;
    }
    return all.firstOrNull;
  }

  static List<FontPairing> search(String query) {
    final q = query.toLowerCase();
    return all.where((p) => p.name.toLowerCase().contains(q) || p.mood.contains(q) || p.bestFor.contains(q) || p.heading.toLowerCase().contains(q)).toList();
  }
}

class FontPairing {
  const FontPairing(this.name, this.cat, this.heading, this.body, this.mood, this.bestFor, this.cssImport, this.notes);
  final String name, cat, heading, body, mood, bestFor, cssImport, notes;

  String get promptHint => 'Font pair: $name — $heading + $body\n  Mood: $mood\n  Import: $cssImport';
}
